const SOURCES = [
  { id:'titanIce', name:'Titan-Ice', pages:['https://www.titan-ice.co.za/hardware/?items_per_page=96&layout=products_without_options&sort_by=timestamp&sort_order=desc'] },
  { id:'dreamware', name:'Dreamware Technology', pages:['https://www.dreamwaretech.co.za/'] },
  { id:'evetech', name:'Evetech', pages:['https://www.evetech.co.za/components','https://www.evetech.co.za/components/nvidia-ati-graphics-cards-21.html'] },
  { id:'wootware', name:'Wootware', pages:['https://www.wootware.co.za/computer-hardware','https://www.wootware.co.za/computer-hardware/video-cards-video-devices'] },
  { id:'takealot', name:'Takealot', pages:['https://www.takealot.com/computers/graphics-cards-26421'] }
];
const RULES=[
 ['GPU',/graphics card|geforce|radeon|quadro|rtx\s*\d|rx\s*\d|arc\s*[ab]\d/i],['CPU',/processor|\bcpu\b|ryzen\s*[3579]|core\s*i[3579]|core\s+ultra|threadripper|xeon|epyc/i],['Motherboard',/motherboard|mainboard|b650|b550|x670|x570|z790|z690|b760|h610|h510|a520/i],['RAM',/\bddr[345]\b|memory|dimm|udimm|sodimm|vengeance|ripjaws|trident z|fury beast/i],['SSD',/\bssd\b|nvme|solid state|990 pro|980 pro|sn770|sn850|mx500|crucial p[35]/i],['HDD',/\bhdd\b|hard drive|hard disk|barracuda|ironwolf/i],['PSU',/power supply|\bpsu\b|80\s*plus|rm650|rm750|rm850|focus gx|supernova|straight power|pure power/i],['Case',/pc case|computer case|chassis|tower|meshify|nzxt.*h[567]|fractal.*north|lancool/i],['CPU Cooler',/cpu cooler|air cooler|aio|liquid cooler|water cooler|deepcool|arctic.*liquid|kraken|nh-d15|hyper 212/i],['Case Fan',/case fan|120mm.*fan|140mm.*fan|pwm fan/i],['Monitor',/monitor|display|ultrawide|odyssey|gaming monitor|\d+\s*hz/i],['Keyboard',/keyboard|keychron|mechanical keyboard/i],['Mouse',/gaming mouse|computer mouse|wireless mouse|deathadder|g502|viper|basilisk/i],['Headset',/headset|headphones|cloud iii|blackshark|arctis/i],['Microphone',/microphone|\bmic\b|quadcast|yeti|seiren/i],['Webcam',/webcam|web camera|c920|c922|brio/i],['Networking',/router|switch|access point|wifi adapter|network adapter|ethernet|wi-fi/i],['Capture Cards',/capture card|elgato/i],['Cables',/hdmi cable|displayport cable|usb cable|ethernet cable|power cable/i],['Speakers',/speaker|soundbar|audio/i],['Gaming Devices',/controller|gamepad|gaming device/i],['UPS',/\bups\b|inverter|power station|surge protector/i],['Accessories',/accessor|stand|bracket|hub|holder|lighting|thermal paste|cable tie|cleaning/i]
];
const MIN={GPU:500,CPU:500,RAM:100,SSD:150,HDD:150,Motherboard:400,PSU:300,Case:250,Monitor:500,Keyboard:100,Mouse:80,Headset:150};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const cat=t=>{for(const[x,r]of RULES)if(r.test(String(t||'')))return x;return'Other'};
const abs=(b,v)=>{try{const u=new URL(String(v||''),b);return /^https?:$/i.test(u.protocol)?u.href:''}catch{return''}};
const strip=v=>clean(String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'"));
function prices(v){const s=String(v||'').replace(/&nbsp;/gi,' '),out=[];const re=/(?:^|[^A-Za-z])(?:R|ZAR)\s*([0-9]{1,3}(?:[\s,][0-9]{3})+|[0-9]{3,6})(?:\.([0-9]{2}))?(?![0-9])/gi;let m;while((m=re.exec(s))){const n=Number(m[1].replace(/[\s,]/g,'')+(m[2]?'.'+m[2]:''));if(Number.isFinite(n))out.push(n)}return out}
function plausible(n,p){const x=Number(p);return Number.isFinite(x)&&x>=10&&x<=1000000&&x>=(MIN[cat(n)]||10)}
function meta(h,n){const e=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]*content=["']([^"']+)["']`,'i');const b=new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,'i');return(h.match(a)||h.match(b))?.[1]||''}
function ld(h){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(h))){try{const v=JSON.parse(m[1].trim()),walk=x=>{if(!x)return;if(Array.isArray(x))return x.forEach(walk);if(typeof x!=='object')return;const t=x['@type'];if(t==='Product'||Array.isArray(t)&&t.includes('Product'))out.push(x);Object.values(x).forEach(walk)};walk(v)}catch{}}return out}
function offer(p){const a=Array.isArray(p?.offers)?p.offers:(p?.offers?[p.offers]:[]);return a[0]||{}}
function image(p,h,b){const a=[];const i=p?.image;if(Array.isArray(i))a.push(...i);else a.push(i);a.push(meta(h,'og:image'),meta(h,'og:image:url'),meta(h,'twitter:image'),meta(h,'twitter:image:src'));const attrs=['src','data-src','data-lazy-src','data-original','data-image','data-flickity-lazyload','data-srcset','srcset'];for(const attr of attrs){const re=new RegExp(`<img[^>]+${attr}=["']([^"']+)["']`,'i');const m=h.match(re);if(m)a.push(m[1].split(',')[0].trim().split(/\s+/)[0])}for(const v of a){if(!v||typeof v==='object')continue;const u=abs(b,v);if(!u||/undefined|null|\[object/i.test(u))continue;if(/logo|placeholder|spinner|favicon|avatar|icon/i.test(u))continue;if(/\.(?:jpe?g|png|webp|avif|gif)(?:[?#].*)?$/i.test(u)||/image|media|cdn/i.test(u))return u}return''}
function canonical(p,h,b){const m=h.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)||h.match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i);return abs(b,p?.url||m?.[1]||b)}
function row(p,h,url,retailer){const o=offer(p),name=clean(p?.name)||strip(meta(h,'og:title'))||strip(meta(h,'twitter:title'));const numericOffer=Number(o?.price);const numericSpec=Number(o?.priceSpecification?.price);const structured=(Number.isFinite(numericOffer)&&plausible(name,numericOffer)?numericOffer:0)||(Number.isFinite(numericSpec)&&plausible(name,numericSpec)?numericSpec:0);const metaPrice=prices(meta(h,'product:price:amount')).find(v=>plausible(name,v));const pr=structured||metaPrice||0;if(!name||!plausible(name,pr))return null;return{id:clean(p?.mpn||p?.sku||name),name,mpn:clean(p?.mpn||p?.sku||''),description:strip(p?.description)||strip(meta(h,'og:description'))||strip(meta(h,'description')),image:image(p,h,url),category:cat(name+' '+(p?.description||'')),offer:{retailer,price:pr,stock:clean(String(o?.availability||'').split('/').pop())||(/out of stock/i.test(h)?'Out of stock':'Check retailer'),url:canonical(p,h,url)}}}
function cardRows(h,b,r){const out=[];for(const p of ld(h)){const x=row(p,h,b,r);if(x)out.push(x)}const re=/<(?:article|li|div)[^>]*>[\s\S]*?<\/(?:article|li|div)>/gi;let m;let guard=0;while((m=re.exec(h))&&guard++<1200){const c=m[0];if(!/(product|item|card|tygh|grid|listing)/i.test(c))continue;const n=strip((c.match(/<(?:h2|h3|h4)[^>]*>([\s\S]*?)<\//i)||[])[1]);if(!n||n.length<8||n.length>220||cat(n)==='Other')continue;const p=prices(strip(c)).find(v=>plausible(n,v));if(!p)continue;const u=(c.match(/href=["']([^"']+)["']/i)||[])[1];const im=(c.match(/<(?:img|source)[^>]+(?:src|data-src|data-lazy-src|data-original|data-srcset|srcset)=["']([^"']+)["']/i)||[])[1];out.push({id:n,name:n,mpn:'',description:'',image:im?abs(b,im.split(',')[0].trim().split(/\s+/)[0]):'',category:cat(n),offer:{retailer:r,price:p,stock:/out of stock|notify me/i.test(c)?'Out of stock':'In Stock',url:abs(b,u)}})}return out}
function productLinks(h,b){const out=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&out.length<30){const u=abs(b,m[1]),t=strip(m[2]);if(!u||!t||t.length<8||t.length>220||cat(t)==='Other')continue;if(/product|products|item|p\//i.test(u)&&!/(category|cart|login|search|wishlist|compare)/i.test(u))out.push(u)}return[...new Set(out)]}
async function detail(url,retailer){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 PCDealFinder/4.0','accept':'text/html,application/xhtml+xml'},cache:'no-store'});if(!r.ok){r.body?.cancel();return null}const h=await r.text();const ps=ld(h);for(const p of ps){const x=row(p,h,url,retailer);if(x)return x}const name=strip(meta(h,'og:title'))||strip(meta(h,'twitter:title'));const pr=prices(h).find(v=>plausible(name,v));if(!name||!pr)return null;return{id:name,name,mpn:'',description:strip(meta(h,'og:description'))||strip(meta(h,'description')),image:image({},h,url),category:cat(name),offer:{retailer,price:pr,stock:/out of stock|notify me/i.test(h)?'Out of stock':'Check retailer',url:canonical({},h,url)}}}catch{return null}}
async function fetchSource(s){let all=[];for(const page of s.pages){try{const r=await fetch(page,{headers:{'user-agent':'Mozilla/5.0 PCDealFinder/4.0','accept':'text/html,application/xhtml+xml'},cache:'no-store'});if(!r.ok){r.body?.cancel();continue}const h=await r.text();all.push(...cardRows(h,page,s.name));for(const link of productLinks(h,page).slice(0,5)){const x=await detail(link,s.name);if(x)all.push(x)}}catch{}}return all}
function productKey(r){return clean(r.mpn||r.name).toLowerCase().replace(/\b(black|white|oc|gaming|edition|desktop graphics card)\b/g,' ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180)}
function mergeRows(rows){const map=new Map();for(const r of rows){if(!r||!r.name||!plausible(r.name,r.offer?.price))continue;const k=productKey(r);if(!k)continue;let p=map.get(k);if(!p){p={id:k,name:r.name,mpn:r.mpn||'',category:r.category,description:r.description||'',image:r.image||'',offers:[]};map.set(k,p)}if(!p.image&&r.image)p.image=r.image;if(!p.description&&r.description)p.description=r.description;const existing=p.offers.find(o=>o.retailer===r.offer.retailer);if(!existing||r.offer.price<existing.price){if(existing)p.offers=p.offers.filter(o=>o!==existing);p.offers.push(r.offer)}}for(const p of map.values())p.offers.sort((a,b)=>a.price-b.price);return[...map.values()].filter(p=>p.offers.length)}
async function tables(db){await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS catalog_products (id TEXT PRIMARY KEY,name TEXT NOT NULL,mpn TEXT,category TEXT NOT NULL,description TEXT,image TEXT,updated_at INTEGER NOT NULL)`),db.prepare(`CREATE TABLE IF NOT EXISTS catalog_offers (product_id TEXT NOT NULL,retailer TEXT NOT NULL,price REAL NOT NULL,stock TEXT,url TEXT,updated_at INTEGER NOT NULL,PRIMARY KEY(product_id,retailer))`),db.prepare(`CREATE TABLE IF NOT EXISTS catalog_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)`)])}
async function getMeta(db,k){try{return(await db.prepare('SELECT value FROM catalog_meta WHERE key=?').bind(k).first())?.value||null}catch{return null}}
async function setMeta(db,k,v){await db.prepare(`INSERT INTO catalog_meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).bind(k,String(v)).run()}
export async function refreshLiveCatalogue(db){await tables(db);const results=await Promise.all(SOURCES.map(async s=>({s,rows:await fetchSource(s)})));const rows=mergeRows(results.flatMap(x=>x.rows));const successful=results.filter(x=>x.rows.length>0);const now=Math.floor(Date.now()/1000);if(successful.length<2)return{imported:rows.length,successfulSources:successful.length,published:false,updatedAt:new Date(now*1000).toISOString()};await db.batch([db.prepare('DELETE FROM catalog_offers'),db.prepare('DELETE FROM catalog_products')]);for(const p of rows){await db.prepare('INSERT OR REPLACE INTO catalog_products(id,name,mpn,category,description,image,updated_at) VALUES(?,?,?,?,?,?,?)').bind(p.id,p.name,p.mpn,p.category,p.description,p.image,now).run();for(const o of p.offers)await db.prepare('INSERT OR REPLACE INTO catalog_offers(product_id,retailer,price,stock,url,updated_at) VALUES(?,?,?,?,?,?)').bind(p.id,o.retailer,o.price,o.stock,o.url,now).run()}await setMeta(db,'last_refresh',new Date(now*1000).toISOString());await setMeta(db,'successful_sources',successful.length);return{imported:rows.length,successfulSources:successful.length,published:true,updatedAt:new Date(now*1000).toISOString()}}
export async function getLiveCatalogue(db){await tables(db);const ps=await db.prepare('SELECT * FROM catalog_products ORDER BY updated_at DESC,name COLLATE NOCASE ASC').all();const os=await db.prepare("SELECT * FROM catalog_offers WHERE retailer NOT LIKE 'PC International%' AND price>=10 AND price<=1000000 ORDER BY price ASC").all();const map=new Map(ps.results.map(p=>[p.id,{id:p.id,name:p.name,mpn:p.mpn,category:p.category,description:p.description,image:p.image||null,updatedAt:p.updated_at,offers:[]} ]));for(const o of os.results){const p=map.get(o.product_id);if(p)p.offers.push({retailer:o.retailer,price:Number(o.price),stock:o.stock||'Check retailer',url:o.url||'',updatedAt:o.updated_at})}return[...map.values()].filter(p=>p.offers.length).map(p=>({...p,offers:p.offers.sort((a,b)=>a.price-b.price)}))}
