const SOURCES=[
{id:'pcInternational',name:'PC International',roots:['https://pcinternational.co.za/product-category/computer-components/processors/','https://pcinternational.co.za/product-category/computer-components/graphics-cards/','https://pcinternational.co.za/products/'],max:12},
{id:'titanIce',name:'Titan-Ice',roots:['https://www.titan-ice.co.za/hardware/processors/','https://www.titan-ice.co.za/hardware/graphics-cards/'],max:10},
{id:'dreamware',name:'Dreamware Technology',roots:['https://www.dreamwaretech.co.za/c/computer-components/graphics-cards-gpus/','https://www.dreamwaretech.co.za/c/computer-components/'],max:10},
{id:'evetech',name:'Evetech',roots:['https://www.evetech.co.za/components','https://www.evetech.co.za/graphics-cards','https://www.evetech.co.za/processors','https://www.evetech.co.za/memory','https://www.evetech.co.za/monitors','https://www.evetech.co.za/gaming-keyboards','https://www.evetech.co.za/gaming-mouse','https://www.evetech.co.za/gaming-accessories'],max:10},
{id:'wootware',name:'Wootware',roots:['https://www.wootware.co.za/computer-hardware','https://www.wootware.co.za/computer-hardware/computer-accessories','https://www.wootware.co.za/pcs-and-laptops/accessories'],max:10},
{id:'takealot',name:'Takealot',roots:['https://www.takealot.com/computers/graphics-cards-26421'],max:6}
];
const RULES=[
['GPU',/graphics card|geforce|radeon|arc\s+[a-z0-9]/i],['CPU',/processor|\bcpu\b|ryzen\s+[3579]|core\s+i[3579]|core\s+ultra|threadripper|xeon|epyc/i],['Motherboard',/motherboard|mainboard|b650|b550|x670|x570|z790|z690|b760|h610|h510|a520/i],['RAM',/\bddr[345]\b|memory|dimm|udimm|sodimm|vengeance|ripjaws|trident z|fury beast/i],['SSD',/\bssd\b|nvme|solid state|990 pro|980 pro|sn770|sn850|mx500/i],['HDD',/\bhdd\b|hard drive|hard disk|barracuda|ironwolf/i],['PSU',/power supply|\bpsu\b|80\s*plus|rm650|rm750|rm850|focus gx|supernova/i],['Case',/pc case|computer case|chassis|tower|meshify|lancool/i],['Case Fan',/case fan|120mm.*fan|140mm.*fan|pwm fan/i],['CPU Cooler',/cpu cooler|air cooler|aio|liquid cooler|water cooler|deepcool|arctic.*liquid|kraken|nh-d15/i],['Monitor',/monitor|display|ultrawide|odyssey|gaming monitor|\d+.*hz/i],['Keyboard',/keyboard|keychron|mechanical keyboard/i],['Mouse',/gaming mouse|computer mouse|wireless mouse|deathadder|g502|viper|basilisk/i],['Headset',/headset|headphones|cloud iii|blackshark|arctis/i],['Microphone',/microphone|\bmic\b|quadcast|yeti|seiren/i],['Webcam',/webcam|web camera|c920|c922|brio/i],['Networking',/router|switch|access point|wifi adapter|network adapter|ethernet|wi-fi/i],['Capture Cards',/capture card|elgato/i],['Cables',/hdmi cable|displayport cable|usb cable|ethernet cable|power cable|adapter|converter/i],['Speakers',/speaker|soundbar|audio/i],['Combos',/keyboard.*mouse.*combo|combo.*keyboard/i],['Gaming Devices',/controller|gamepad|gaming device/i],['UPS',/ups|inverter|power station|surge protector/i],['Docking',/docking station|dock/i],['Bags',/laptop bag|backpack|carry bag/i],['Laptop',/laptop|notebook|macbook/i],['Desktop',/desktop pc|office pc|gaming pc|mini pc/i],['Printer',/printer|scanner|toner|cartridge/i],['Projector',/projector/i],['Accessories',/accessor|stand|bracket|hub|holder|lighting|thermal paste|cable tie|cleaning/i]
];
const category=text=>{for(const[c,r]of RULES)if(r.test(text))return c;return'Other'};
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const price=s=>{const m=String(s||'').replace(/\s/g,'').replace(/,/g,'').match(/(?:R|ZAR)?([0-9]+(?:\.[0-9]{1,2})?)/i);return m?Number(m[1]):0};
const absUrl=(base,u)=>{try{return new URL(u,base).href}catch{return''}};
const stripHtml=s=>clean(String(s||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' '));
function jsonLd(html){const out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const v=JSON.parse(m[1]);const walk=x=>{if(!x)return;if(Array.isArray(x))return x.forEach(walk);if(typeof x==='object'){const t=x['@type'];if(t==='Product'||(Array.isArray(t)&&t.includes('Product')))out.push(x);Object.values(x).forEach(walk)}};walk(v)}catch{}}return out}
function htmlProducts(html,base,retailer){const ld=jsonLd(html).map(p=>{const o=Array.isArray(p.offers)?p.offers[0]:(p.offers||{}),img=Array.isArray(p.image)?p.image[0]:p.image,n=clean(p.name),u=p.url||o.url;return n?{id:p.sku||p.mpn||n,name:n,mpn:p.mpn||p.sku||'',description:stripHtml(p.description||''),image:absUrl(base,img),category:category([n,p.description,p.mpn].join(' ')),offer:{retailer,price:price(o.price),stock:String(o.availability||'').split('/').pop()||'Check retailer',url:absUrl(base,u)}}:null}).filter(x=>x&&x.offer.price>0);if(ld.length)return ld;const blocks=html.match(/<(?:article|li|div)[^>]*class=["'][^"']*(?:product|item|card)[^"']*["'][\s\S]*?<\/(?:article|li|div)>/gi)||[];return blocks.map(b=>{const n=stripHtml((b.match(/<(?:h2|h3|h4)[^>]*>([\s\S]*?)<\//i)||[])[1]),p=(b.match(/(?:R|ZAR)\s?([0-9][0-9\s,.]*)/i)||[])[1],a=(b.match(/href=["']([^"']+)["']/i)||[])[1],im=(b.match(/<img[^>]+(?:src|data-src|data-lazy-src)=['"]([^'"]+)['"]/i)||[])[1];return n&&price(p)?{id:n,name:n,mpn:'',description:'',image:absUrl(base,im),category:category(n),offer:{retailer,price:price(p),stock:'Check retailer',url:absUrl(base,a)}}:null}).filter(Boolean)}
function urlsFromXml(xml){return [...xml.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)].map(m=>m[1].trim()).filter(Boolean)}
function urlsFromHtml(html,base){const out=[];for(const m of html.matchAll(/href=["']([^"']+)["']/gi)){const u=absUrl(base,m[1]);if(u&&productUrl(u))out.push(u)}return [...new Set(out)]}
function productUrl(u){return /product|products|item|\/p\/|shop|sku/i.test(u)&&!/(category|tag|brand|author|cart|checkout|account|search|page\/\d+)/i.test(u)}
async function fetchText(url,accept='text/html,application/xhtml+xml'){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 PCDealFinder/1.0','accept}});if(!r.ok)return null;return await r.text()}catch(e){console.log('fetch failed',url,String(e));return null}}
async function discover(root){const text=await fetchText(root,'application/xml,text/xml,text/html,application/xhtml+xml');if(!text)return[];const xml=urlsFromXml(text);return xml.length?xml:urlsFromHtml(text,root)}
async function getMeta(db,key,fallback){const r=await db.prepare('SELECT value FROM catalog_meta WHERE key=?').bind(key).first();return r?Number(r.value)||fallback:fallback}
async function setMeta(db,key,value){await db.prepare("INSERT INTO catalog_meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,String(value)).run()}
async function ensureTables(db){await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS catalog_products (id TEXT PRIMARY KEY,name TEXT NOT NULL,mpn TEXT,category TEXT NOT NULL,description TEXT,image TEXT,updated_at INTEGER NOT NULL)`),db.prepare(`CREATE TABLE IF NOT EXISTS catalog_offers (product_id TEXT NOT NULL,retailer TEXT NOT NULL,price REAL NOT NULL,stock TEXT,url TEXT,updated_at INTEGER NOT NULL,PRIMARY KEY(product_id,retailer))`),db.prepare(`CREATE TABLE IF NOT EXISTS catalog_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)`)])}
async function saveRows(db,rows){const now=Math.floor(Date.now()/1000);for(const r of rows){const id=String(r.mpn||r.id||r.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,180);await db.prepare(`INSERT INTO catalog_products(id,name,mpn,category,description,image,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,mpn=excluded.mpn,category=excluded.category,description=CASE WHEN excluded.description<>'' THEN excluded.description ELSE catalog_products.description END,image=CASE WHEN excluded.image<>'' THEN excluded.image ELSE catalog_products.image END,updated_at=excluded.updated_at`).bind(id,r.name,r.mpn,r.category,r.description||'',r.image||'',now).run();await db.prepare(`INSERT INTO catalog_offers(product_id,retailer,price,stock,url,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(product_id,retailer) DO UPDATE SET price=excluded.price,stock=excluded.stock,url=excluded.url,updated_at=excluded.updated_at`).bind(id,r.offer.retailer,r.offer.price,r.offer.stock,r.offer.url,now).run()}}
async function importPage(url,retailer){const html=await fetchText(url);return html?htmlProducts(html,url,retailer):[]}
export async function refreshLiveCatalogue(db){await ensureTables(db);let imported=0,visited=0;for(const s of SOURCES){let urls=[];for(const root of s.roots){const direct=await importPage(root,s.name);visited++;if(direct.length){await saveRows(db,direct);imported+=direct.length;continue}const found=await discover(root);urls.push(...found);if(urls.length>120)break}urls=[...new Set(urls)].filter(productUrl);let cursor=await getMeta(db,`url_${s.id}`,0);if(cursor>=urls.length)cursor=0;const batch=urls.slice(cursor,cursor+s.max);const rows=[];for(const u of batch){const r=await importPage(u,s.name);if(r.length){rows.push(...r);imported+=r.length}visited++}if(rows.length)await saveRows(db,rows);await setMeta(db,`url_${s.id}`,cursor+batch.length>=urls.length?0:cursor+batch.length)}const stamp=new Date().toISOString();await setMeta(db,'last_refresh',stamp);return{imported,visited,updatedAt:stamp}}
export async function getLiveCatalogue(db){await ensureTables(db);const p=await db.prepare('SELECT * FROM catalog_products ORDER BY name').all(),o=await db.prepare('SELECT * FROM catalog_offers WHERE price>0 AND updated_at>? ORDER BY price').bind(Math.floor(Date.now()/1000)-604800).all();const map=new Map(p.results.map(x=>[x.id,{id:x.id,name:x.name,mpn:x.mpn,category:x.category,description:x.description,image:x.image,offers:[]} ]));for(const x of o.results){const v=map.get(x.product_id);if(v)v.offers.push({retailer:x.retailer,price:x.price,stock:x.stock,url:x.url,updatedAt:x.updated_at})}return[...map.values()].filter(x=>x.offers.length)}
