/* PCDealFinder — Smart Builder v2 */
(function(){
const root=document.getElementById('pcdfRecommendationWizard');if(!root)return;
const money=n=>'R'+Math.round(n||0).toLocaleString('en-ZA');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
root.innerHTML=`<div class="smartWizardShell"><div class="wizardTop"><div><span class="wizardKicker">SMART BUILD ENGINE</span><h2>Build your dream PC.</h2><p>Set the target. We'll do the shopping math.</p></div><div class="wizardPulse"><i></i><span>LIVE CATALOGUE</span></div></div><div class="wizardSteps"><span class="active"><b>01</b> Budget</span><span><b>02</b> Purpose</span><span><b>03</b> Performance</span></div><div class="recGrid wizardGrid"><label><span>Budget</span><select id="recBudget"><option value="10000">R10,000</option><option value="15000" selected>R15,000</option><option value="20000">R20,000</option><option value="25000">R25,000</option><option value="30000">R30,000</option><option value="40000">R40,000+</option><option value="50000">R50,000</option></select></label><label><span>Use</span><select id="recUse"><option value="gaming">🎮 Gaming</option><option value="streaming">🎥 Gaming + Streaming</option><option value="editing">🎬 Editing</option><option value="general">💻 General use</option></select></label><label><span>Resolution</span><select id="recResolution"><option>1080p</option><option selected>1440p</option><option>4K</option></select></label><label><span>Priority</span><select id="recPriority"><option value="value">💰 Best value</option><option value="performance">⚡ Maximum performance</option><option value="balanced">⚖️ Balanced</option></select></label></div><button id="recGenerate" class="recGenerate"><span>Generate my build</span><b>→</b></button><div class="wizardHint"><span>✦</span> Uses the PCDealFinder catalogue to find a price-balanced starting point.</div><div id="recResult"></div></div>`;
const result=root.querySelector('#recResult');
const price=p=>{const a=(p.offers||[]).map(o=>Number(o.price)).filter(n=>Number.isFinite(n)&&n>0);return a.length?Math.min(...a):Infinity};
const category=p=>String(p.category||'').toLowerCase().replace(/[^a-z]/g,'');
const aliases={cpu:['cpu','processor'],gpu:['gpu','graphicscard','graphics'],ram:['ram','memory'],ssd:['ssd','solidstatedrive','storage'],psu:['psu','powersupply']};
function candidates(items,cat){const allowed=aliases[cat]||[cat];return items.filter(p=>allowed.includes(category(p))&&price(p)<Infinity)}
function pick(items,cat,target,priority){let a=candidates(items,cat);if(!a.length)return null;const score=p=>{const ratio=price(p)/target;let s=Math.abs(Math.log(Math.max(ratio,.01)));if(priority==='value')s+=price(p)/Math.max(target,1)*.15;if(priority==='performance')s-=Math.min(price(p)/Math.max(target,1),2)*.08;return s};return a.sort((x,y)=>score(x)-score(y))[0]}
root.querySelector('#recGenerate').onclick=async()=>{const button=root.querySelector('#recGenerate');button.classList.add('loading');button.disabled=true;result.innerHTML='<div class="recLoading"><span></span><span></span><span></span><b>Building your recommendation…</b></div>';const budget=Number(root.querySelector('#recBudget').value),res=root.querySelector('#recResolution').value,use=root.querySelector('#recUse').value,priority=root.querySelector('#recPriority').value;try{const response=await fetch('data.json?v=20260817-smart2',{cache:'no-store'});if(!response.ok)throw Error('catalogue');const items=await response.json();let gpu=res==='4K'?.48:res==='1440p'?.38:.32,cpu=.22,ram=.10,ssd=.08,psu=.09;if(use==='editing'){cpu=.26;gpu=.34;ram=.14;ssd=.09}if(use==='streaming'){cpu=.24;gpu=.38;ram=.12;ssd=.08}if(priority==='performance'){gpu+=.06;cpu+=.02;ssd-=.02;ram-=.02}if(priority==='value'){gpu-=.03;ssd+=.02;psu+=.01}const targets={gpu:budget*gpu,cpu:budget*cpu,ram:budget*ram,ssd:budget*ssd,psu:budget*psu};const parts=['cpu','gpu','ram','ssd','psu'].map(c=>pick(items,c,targets[c],priority)).filter(Boolean);const total=parts.reduce((s,p)=>s+price(p),0);result.innerHTML=`<div class="recResult recResultAnimated"><div class="recResultHead"><div><small>YOUR RECOMMENDED BUILD</small><h3>${esc(res)} ${esc(use)} rig</h3><p>${esc(root.querySelector('#recPriority').selectedOptions[0].text)} · Budget ${money(budget)}</p></div><strong>${money(total)}</strong></div><div class="recParts">${parts.map((p,i)=>`<div style="--delay:${i*70}ms"><span>${esc(p.category||'Part')}</span><b>${esc(p.name)}</b><strong>${money(price(p))}</strong></div>`).join('')}</div><div class="recFooter"><span>✦ ${parts.length}/5 core components found</span><small>Prices are catalogue starting points. Check compatibility before buying.</small></div></div>`}catch(e){result.innerHTML='<div class="recResult recError recResultAnimated"><strong>We couldn’t load the catalogue.</strong><p>Refresh the page and try the Smart Builder again.</p></div>'}finally{button.classList.remove('loading');button.disabled=false}};
})();
