/* PCDealFinder — Phase 4 recommendation wizard */
(function(){
  const root=document.getElementById('pcdfRecommendationWizard'); if(!root)return;
  const money=n=>'R'+Math.round(n||0).toLocaleString('en-ZA');
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  root.innerHTML=`<div class="recHead"><small>PCDEALFINDER SMART BUILDER</small><h2>Find the right PC for your budget.</h2><p>Tell us what you need and we'll choose from the real catalogue.</p></div><div class="recGrid"><label>Budget<select id="recBudget"><option value="10000">R10,000</option><option value="15000" selected>R15,000</option><option value="20000">R20,000</option><option value="25000">R25,000</option><option value="30000">R30,000</option><option value="40000">R40,000+</option></select></label><label>Use<select id="recUse"><option value="gaming">🎮 Gaming</option><option value="streaming">🎥 Gaming + Streaming</option><option value="editing">🎬 Editing</option><option value="general">💻 General use</option></select></label><label>Resolution<select id="recResolution"><option>1080p</option><option selected>1440p</option><option>4K</option></select></label><label>Priority<select id="recPriority"><option value="value">💰 Best value</option><option value="performance">⚡ Maximum performance</option><option value="balanced">⚖️ Balanced</option></select></label></div><button id="recGenerate" class="recGenerate">Build my recommendation →</button><div id="recResult"></div>`;
  const result=root.querySelector('#recResult');
  function price(p){return Math.min(...(p.offers||[]).map(o=>Number(o.price)).filter(Boolean),Infinity)}
  function pick(items,cat,budget){const a=items.filter(p=>String(p.category||'').toLowerCase()===cat&&price(p)<Infinity).sort((x,y)=>price(x)-price(y));if(!a.length)return null;const target=budget*(cat==='gpu'?.38:cat==='cpu'?.22:cat==='ram'?.10:cat==='ssd'?.08:cat==='psu'?.10:.12);return [...a].sort((x,y)=>Math.abs(price(x)-target)-Math.abs(price(y)-target))[0]}
  root.querySelector('#recGenerate').onclick=()=>fetch('data.json?v=20260817',{cache:'no-store'}).then(r=>r.json()).then(items=>{const budget=Number(root.querySelector('#recBudget').value),res=root.querySelector('#recResolution').value,use=root.querySelector('#recUse').value;let gpuShare=res==='4K'?.48:res==='1440p'?.40:.32;if(use==='editing')gpuShare=.34;const cats=['cpu','gpu','ram','ssd','psu'];const weights={cpu:.22,gpu:gpuShare,ram:.10,ssd:.08,psu:.10};let parts=[];for(const c of cats){const p=pick(items,c,budget*weights[c]/(c==='gpu'?.40:.22));if(p)parts.push(p)}let total=parts.reduce((s,p)=>s+price(p),0);result.innerHTML=`<div class="recResult"><div class="recResultHead"><div><small>RECOMMENDED BUILD</small><h3>${esc(res)} ${esc(use)} setup</h3><p>${root.querySelector('#recPriority').selectedOptions[0].text} · Target budget ${money(budget)}</p></div><strong>${money(total)}</strong></div><div class="recParts">${parts.map(p=>`<div><span>${esc(p.category||'Part')}</span><b>${esc(p.name)}</b><strong>${money(price(p))}</strong></div>`).join('')}</div><div class="recNote">💡 This recommendation uses current catalogue prices. Check the Builder's compatibility warnings before buying.</div></div>`}).catch(()=>{result.innerHTML='<div class="recError">Could not load the catalogue. Please try again.</div>'});
})();
