const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
// Phase 15B deployment marker: ensure the production build consumes the current auth worker.
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});
const uid=()=>crypto.randomUUID();
const bytesHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const hexBytes=h=>new Uint8Array((h.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,256);return bytesHex(bits)}
async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16));return `${bytesHex(salt)}$${await derive(password,salt)}`}
async function verifyPassword(password,stored){const [s,h]=String(stored||'').split('$');if(!s||!h)return false;return (await derive(password,hexBytes(s)))===h}
function cookieSession(id,maxAge=2592000){return `pcdf_session=${id}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`}
function sessionId(request){return (request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pcdf_session='))?.slice(13)||null}
async function initDb(db){await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL DEFAULT '',password_hash TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT (unixepoch()),updated_at INTEGER NOT NULL DEFAULT (unixepoch()))"),db.prepare('CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL DEFAULT (unixepoch()),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)'),db.prepare('CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id)'),db.prepare('CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at)')])}
async function currentUser(request,db){const sid=sessionId(request);if(!sid)return null;const now=Math.floor(Date.now()/1000);return await db.prepare('SELECT u.id,u.email,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').bind(sid,now).first()}
async function body(request){try{return await request.json()}catch{return {}}}
export default{async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);if(!env.DB)return json({ok:false,error:'D1 binding missing'},503);try{await initDb(env.DB);
if(url.pathname==='/api/health')return json({ok:true,service:'pcdealfinder',database:true});
if(url.pathname==='/api/db-test'){const r=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all();return json({ok:true,tables:r.results.map(x=>x.name)});}
if(url.pathname==='/api/db-schema'){const r=await env.DB.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name IN ('users','sessions') ORDER BY name").all();const info={};for(const t of r.results){const cols=await env.DB.prepare(`PRAGMA table_info(${t.name})`).all();info[t.name]={sql:t.sql,columns:cols.results}}return json({ok:true,schema:info});}
if(url.pathname==='/api/auth/signup'&&request.method==='POST'){const b=await body(request),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),name=(String(b.name||'').trim().slice(0,40)||email.split('@')[0].slice(0,40));if(!/^\S+@\S+\.\S+$/.test(email))return json({ok:false,error:'Enter a valid email address'},400);if(password.length<8)return json({ok:false,error:'Password must be at least 8 characters'},400);if(password.length>128)return json({ok:false,error:'Password is too long'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(exists)return json({ok:false,error:'An account with that email already exists'},409);const id=uid(),stored=await hashPassword(password),sid=uid(),expires=Math.floor(Date.now()/1000)+2592000;await env.DB.prepare('INSERT INTO users(id,email,display_name,password_hash) VALUES(?,?,?,?)').bind(id,email,name,stored).run();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,id,expires).run();return json({ok:true,user:{id,email,displayName:name},authenticated:true},200,{"set-cookie":cookieSession(sid)});}
if(url.pathname==='/api/auth/login'&&request.method==='POST'){const b=await body(request),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),u=await env.DB.prepare('SELECT id,email,display_name,password_hash FROM users WHERE email=?').bind(email).first();if(!u||!(await verifyPassword(password,u.password_hash)))return json({ok:false,error:'Email or password is incorrect'},401);const sid=uid(),expires=Math.floor(Date.now()/1000)+2592000;await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,u.id,expires).run();return json({ok:true,user:{id:u.id,email:u.email,displayName:u.display_name||''},authenticated:true},200,{"set-cookie":cookieSession(sid)});}
if(url.pathname==='/api/auth/me'&&request.method==='GET'){const u=await currentUser(request,env.DB);return json({ok:true,authenticated:!!u,user:u?{id:u.id,email:u.email,displayName:u.display_name||''}:null});}
if(url.pathname==='/api/auth/logout'&&request.method==='POST'){const sid=sessionId(request);if(sid)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return json({ok:true},200,{"set-cookie":cookieSession('',0)});}
if(url.pathname==='/api/auth/profile'&&request.method==='PATCH'){const u=await currentUser(request,env.DB);if(!u)return json({ok:false,error:'Not signed in'},401);const b=await body(request),name=String(b.name||'').trim().slice(0,40),displayName=name||u.email.split('@')[0].slice(0,40);await env.DB.prepare('UPDATE users SET display_name=?,updated_at=unixepoch() WHERE id=?').bind(displayName,u.id).run();return json({ok:true,user:{id:u.id,email:u.email,displayName}});}
return json({ok:false,error:'Not found'},404);
}catch(error){console.error('API ERROR',error);return json({ok:false,error:'Server error: '+(error?.message||String(error))},500)}}};
